```{r}
#Limpieza de tabla de número de doctores
```

```{r}
library(htmltab)
```

```{r}
LinkDoc="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/359.html"

Link_path_doc='//*[@id="fieldListing"]'
```

```{r}
Medicos= htmltab (doc = LinkDoc,which = Link_path_doc)
```

```{r}
names(Medicos)
names(Medicos)= c ("Pais", "Numero_medicos")
```

```{r}
library(tidyr)
```


```{r}
Medicos=separate(Medicos,Numero_medicos,into=c("Numero_medicos",'delete'), "\\ ")[,-3]
```

```{r}
table(Medicos$Medicos, useNA= 'always')
```

```{r}
Medicos<-na.omit(Medicos)
Medicos
```

```{r}
str(Medicos)
```

```{r}
Medicos$Numero_medicos=as.numeric(Medicos$Numero_medicos)
```

```{r}
Medicos<-na.omit(Medicos)
Medicos
```




```{r}
#Nos  quedarnos con los paises que son de europa y america 
```


```{r}
library(rio)
```



```{r}
Europa_America1="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls"

EuroAmer1=import(Europa_America1)

```


```{r}
names(EuroAmer1)
```


```{r}
names(EuroAmer1)= c ("Pais")
```


```{r}
Medicos_EA =merge(Medicos,EuroAmer1,by.x='Pais', by.y='Pais') 
head(Medicos_EA)
```

```{r}
## salen 81 paises 
```


