```{r}
#Saneamiento
```

```{r}
library(htmltab)
```

```{r}
Linksana="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/398.html"

Link_path_sana='//*[@id="fieldListing"]'
```

```{r}
saneamiento= htmltab (doc = Linksana,which = Link_path_sana)
```

```{r}
names(saneamiento)
names(saneamiento)= c ("Pais", "Porcentaje_Saneamiento")
```


```{r}
library(tidyr)
```

```{r}
saneamiento$Porcentaje_Saneamiento=gsub("\\%.*","",saneamiento$Porcentaje_Saneamiento)
```

```{r}
saneamiento$Porcentaje_Saneamiento=gsub(".*\\:","",saneamiento$Porcentaje_Saneamiento)
```

```{r}
table(saneamiento$saneamiento, useNA= 'always')
```

```{r}
saneamiento<-na.omit(saneamiento)
```

```{r}
str(saneamiento)
```

```{r}
saneamiento$Porcentaje_Saneamiento=as.numeric(saneamiento$Porcentaje_Saneamiento)
```

```{r}
saneamiento<-na.omit(saneamiento)
```

```{r}
library(rio)
```

```{r}
Europa_America3="https://github.com/IvonneMM/Covid_trabajogrupal/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1)%20(4).xls"

EuroAmer3=import(Europa_America3)
```

```{r}
names(EuroAmer3)
```

```{r}
names(EuroAmer3)= c ("Pais")
```

```{r}
Saneamiento_EA =merge(saneamiento,EuroAmer3,by.x='Pais', by.y='Pais') 
head(Saneamiento_EA)
```

